a = int(input("Enter Your First:\n"))
b = int(input("Enter Your Second:\n"))
print("=" * 50)
print("\tArithmatic operators")
print(f"sum = ({a},{b}) = {a + b}")
print(f"sum = ({a},{b}) = {a - b}")
print(f"sum = ({a},{b}) = {a * b}")
print(f"sum = ({a},{b}) = {a / b}")
print(f"sum = ({a},{b}) = {a // b}")
print(f"sum = ({a},{b}) = {a ** b}")
print("*" * 50)
