a, b = int(input("Enter a number:\n")), int(input("Enter b number:\n"))
sum, sub, mul, div, fdiv, mod, exp = a + b, a - b, a * b, a / b, a // b, a % b, a ** b
print("#" * 50)
print("sum = ", sum)
print("sub = ", sub)
print("Mul = ", mul)
print("Div = ", div)
print("Floor Division = ", fdiv)
print("Mod = ", mod)
print(f"The Exponential Value is {a},{b} = {a**b} ")
print("#" * 50)
