a,b = float(input("Enter a Number:\n")),float(input("Enter a Number:\n"))
print("\tResult of Relational  Operator is Given Below:")
print("="*45)
print(f"\ta={a},b={b},a>b={a>b}")
print(f"\ta={a},b={b},a<b={a<b}")
print(f"\ta={a},b={b},a==b={a==b}")
print(f"\ta={a},b={b},a!=b={a!=b}")
print(f"\ta={a},b={b},a>=b={a>=b}")
print(f"\ta={a},b={b},a<=b={a<=b}")
print("*"*45)